name: Fund Daily Push

on:
  push:
    branches:
      - main
  schedule:
    # 每个工作日北京时间 14:40 运行（UTC 时间为 06:40）
    - cron: '30 6 * * 1-5'
  workflow_dispatch: # 手动触发

jobs:
  run-fund-script:
    runs-on: ubuntu-latest
    env:
      SERVER_KEY: ${{ secrets.SERVER_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Fund Script
        run: |
          echo "=== 开始运行基金爬取推送脚本 ==="
          python fund.py
          echo "=== 脚本运行结束 ==="

      - name: Check for errors
        if: failure()
        run: echo "❌ 基金推送脚本运行失败，请检查日志！"
